[package]
name = "aeon-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
biodivine-lib-param-bn = "0.5.9"
getrandom = { version = "0.2", features = ["js"]}
regex = "1.10"
